name: Firebase Automatic Deployment Workflow

on:
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  test:
    name: Test Job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
    - name: Install dependencies
      run: yarn install
    - name: Test Run
      run: yarn test
    - name: Test Succeeded
      if: ${{ success() }}
      run: echo "successed"
    - name: Test Failed
      if: ${{ failure() }}
      run: echo "failed"

  build:
    name: Build Job
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
    - name: Install dependencies
      run: yarn install
    - name: build
      run: yarn generate
    - name: Upload Dist
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: dist/
    - name: Build Succeeded
      if: ${{ success() }}
      run: echo "successed"
    - name: Build Failed
      if: ${{ failure() }}
      run: echo "failed"

  deploy:
    name: Deploy Job
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/download-artifact@v2
      with:
        name: dist
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
    - name: Firebase CLI install
      run: npm install -g firebase-tools
    - name: deploy
      run: firebase deploy --project=${{ secrets.PROD_PROJECT_ID }} --token ${{ secrets.FIREBASE_TOKEN }}
    - name: Deploy Succeeded
      if: ${{ success() }}
      run: echo "successed"
    - name: Deploy Failed
      if: ${{ failure() }}
      run: echo "failed"
