name: Firebase Automatic Deployment Workflow

on:
  pull_request:
    branches:
    - master
    types:
    - closed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.12.0'
    - name: Install dependencies
      run: yarn install
    - name: Test Run
      run: yarn test
    - name: build
      run: echo "Build"
    - name: deploy
      run: echo "Deploy"
    - name: The job has succeeded
      if: ${{ success() }}
      run: echo "successed"
    - name: The job has failed
      if: ${{ failure() }}
      run: echo "failed"
